"""init

Revision ID: 40e8a4ecc389
Revises:
Create Date: 2019-03-04 22:16:33.768961

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '40e8a4ecc389'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'restaurant',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('tabelog_restaurant_id', sa.Integer(), nullable=False),
        sa.Column('tags', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tabelog_restaurant_id')
    )
    op.create_table(
        'tabelog_restaurant',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_url', sa.String(length=300), nullable=False),
        sa.Column('url', sa.String(length=300), nullable=True),
        sa.Column('rate', sa.Float(), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('tel', sa.String(length=100), nullable=True),
        sa.Column('images', sa.String(), nullable=True),
        sa.Column('lunch_rate', sa.Float(), nullable=True),
        sa.Column('dinner_rate', sa.Float(), nullable=True),
        sa.Column('lunch_price_min', sa.Integer(), nullable=True),
        sa.Column('lunch_price_max', sa.Integer(), nullable=True),
        sa.Column('dinner_price_min', sa.Integer(), nullable=True),
        sa.Column('dinner_price_max', sa.Integer(), nullable=True),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lng', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabelog_restaurant')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
