"""init

Revision ID: b75c621cef34
Revises:
Create Date: 2018-09-05 22:55:30.875744

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b75c621cef34'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name_ja', sa.String(length=100), nullable=True),
        sa.Column('name_en', sa.String(length=100), nullable=True),
        sa.Column('name_cn', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name_ja')
    )
    op.create_table(
        'offday',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name_ja', sa.String(length=100),
                  nullable=False),
        sa.Column('name_en', sa.String(length=100),
                  nullable=False),
        sa.Column('name_cn', sa.String(length=100),
                  nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'restaurant',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('url', sa.String(length=300), nullable=True),
        sa.Column('tel', sa.String(length=100), nullable=True),
        sa.Column('images', sa.String(), nullable=True),
        sa.Column('tabelog_id', sa.String(length=100),
                  nullable=True),
        sa.Column('tabelog_url', sa.String(length=300),
                  nullable=True),
        sa.Column('tabelog_rate', sa.Float(), nullable=True),
        sa.Column('tabelog_lunch_rate', sa.Float(), nullable=True),
        sa.Column('tabelog_lunch_price_min', sa.Integer(),
                  nullable=True),
        sa.Column('tabelog_lunch_price_max', sa.Integer(),
                  nullable=True),
        sa.Column('tabelog_dinner_rate', sa.Float(),
                  nullable=True),
        sa.Column('tabelog_dinner_price_min', sa.Integer(),
                  nullable=True),
        sa.Column('tabelog_dinner_price_max', sa.Integer(),
                  nullable=True),
        sa.Column('tabelog_address', sa.Text(), nullable=True),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lng', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tabelog_id')
    )
    op.create_table(
        'tag',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name_ja', sa.String(length=100), nullable=True),
        sa.Column('name_en', sa.String(length=100), nullable=True),
        sa.Column('name_cn', sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'restaurant_category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('restaurant_id', sa.Integer(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'],
                                ['category.id'], ),
        sa.ForeignKeyConstraint(['restaurant_id'],
                                ['restaurant.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'restaurant_offday',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('restaurant_id', sa.Integer(), nullable=True),
        sa.Column('offday_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['offday_id'], ['offday.id'], ),
        sa.ForeignKeyConstraint(['restaurant_id'],
                                ['restaurant.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'restaurant_tag',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('restaurant_id', sa.Integer(), nullable=True),
        sa.Column('tag_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['restaurant_id'],
                                ['restaurant.id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('restaurant_tag')
    op.drop_table('restaurant_offday')
    op.drop_table('restaurant_category')
    op.drop_table('tag')
    op.drop_table('restaurant')
    op.drop_table('offday')
    op.drop_table('category')
